services:
  # DB 서버 (2칸 들여쓰기)
  db:
    image: postgres:15
    container_name: board-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./db_data:/var/lib/postgresql/data
    networks:
      - board-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  # Push 서버 (2칸 들여쓰기)
  push-server:
    image: yeonhyukkim/fake-push-server:latest
    container_name: push-server
    restart: always
    networks:
      - board-net

  # 게시판 서버 (2칸 들여쓰기)
  board-server:
      build: .
      container_name: board-server
      restart: always
      ports:
        - '3000:3000'
      env_file:
        - .env  # 기존 .env 파일에 있는 모든 변수(JWT_SECRET, CLIENT_ID 등)를 통째로 가져옴
      environment:
        # 도커 내부 통신을 위해 변경해야 하는 주소만 덮어쓰기
        - DATABASE_URL=postgresql://postgres:123456789@db:5432/postgres?schema=public
        - pushUrL=http://push-server:8090 # 기존 .env의 pushUrL을 도커 컨테이너용 주소로 오버라이드
      depends_on:
        db:
          condition: service_healthy
        push-server:
          condition: service_started
      networks:
        - board-net

# 네트워크 설정 (최상단 0칸 들여쓰기)
networks:
  board-net:
    driver: bridge